### ISSUE TITLE
Optional values

### ISSUE THREAD

**Issue by Caellian** [sirwhinesalot/table-enum#2]
I suggest you add support for optional values through `#[optional]` attibute like:

```rust
table_enum! {
    enum BinaryOp(text: &'static str, #[optional] precedence: i32) {
        Add("+", 10),
        Sub("-", 10),
        Mul("*", _),
        Div("/", 20),
        Pow("**", _),
        ...
    }
}
```

which would generate:

```rust
enum BinaryOp {
    Add,
    Sub,
    Mul,
    Div,
    Pow,
    ...
}
impl BinaryOp {
    // text fn normally
    const fn precedence(&self) -> Option<i32> {
        match self {
            BinaryOp::Add => Some(10),
            BinaryOp::Sub => Some(10),
            BinaryOp::Div => Some(20),
            ...
            _ => return None
        }
    }
}
```

It could work with #1 by omitting init of those fields from LUT. Accessing those fields would be UB (i.e. garbage values). You could either produce an error when those attributes are combined or specify it's UB in the documentation and shift the responsibility on end-users to provide their own sentinel value.

**Comment by sirwhinesalot** [comment]
That would be more convenient than having to write Some(10) or None everywhere for sure.
I'll add it as soon as I have the time.

**Comment by sirwhinesalot** [comment]
Done, but with ` #[option]` instead of `#[optional]` and an extra #[default] for good measure, thanks for the idea!
